In [1]:
from Korpora import Korpora
import pandas as pd

In [2]:
corpus = Korpora.load("korean_hate_speech")

train_df = pd.DataFrame(corpus.train)
dev_df = pd.DataFrame(corpus.dev)

print(train_df.shape)
print(dev_df.shape)
train_df.head()

    Korpora 는 다른 분들이 연구 목적으로 공유해주신 말뭉치들을
    손쉽게 다운로드, 사용할 수 있는 기능만을 제공합니다.

    말뭉치들을 공유해 주신 분들에게 감사드리며, 각 말뭉치 별 설명과 라이센스를 공유 드립니다.
    해당 말뭉치에 대해 자세히 알고 싶으신 분은 아래의 description 을 참고,
    해당 말뭉치를 연구/상용의 목적으로 이용하실 때에는 아래의 라이센스를 참고해 주시기 바랍니다.

    # Description
    Authors :
        - Jihyung Moon* (inmoonlight@github)
        - Won Ik Cho* (warnikchow@github)
        - Junbum Lee (beomi@github)
        * equal contribution
    Repository : https://github.com/kocohub/korean-hate-speech
    References :
        - Moon, J., Cho, W. I., & Lee, J. (2020). BEEP! Korean Corpus of Online News
          Comments for Toxic Speech Detection. arXiv preprint arXiv:2005.12503.

    We provide the first human-annotated Korean corpus for toxic speech detection and the large unlabeled corpus.
    The data is comments from the Korean entertainment news aggregation platform.

    # License
    Creative Commons Attribution-ShareAlike 4.0 International License.
    Visit here for detail : https://creativecommons.org/licenses/by-sa/4.0/

[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/unlabeled/unlabeled_comments_1.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/unlabeled/unlabeled_comments_2.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/unlabeled/unlabeled_comments_3.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/unlabeled/unlabeled_comments_4.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/unlabeled/unlabeled_comments_5.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/unlabeled_comments.news_title_1.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/unlabeled_comments.news_title_2.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/unlabeled_comments.news_title_3.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/unlabeled_comments.news_title_4.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/unlabeled_comments.news_title_5.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/dev.news_title.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/test.news_title.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/news_title/train.news_title.txt
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/labeled/dev.tsv
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/labeled/train.tsv
[Korpora] Corpus `korean hate speech` is already installed at /Users/pyojeongin/Korpora/korean_hate_speech/test.no_label.tsv
(7896, 5)
(471, 5)

,text,title,gender_bias,bias,hate
0,(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속...,"""밤새 조문 행렬…故 전미선, 동료들이 그리워하는 따뜻한 배우 [종합]""",False,others,hate
1,....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을...,"""'연중' 故 전미선, 생전 마지막 미공개 인터뷰…환하게 웃는 모습 '먹먹'[종합]""",False,none,none
2,"...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래...","""[단독] 잔나비, 라디오 출연 취소→'한밤' 방송 연기..비판 여론 ing(종합)""",False,none,hate
3,"1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데","""'아스달 연대기' 장동건-김옥빈, 들끓는 '욕망커플'→눈물범벅 '칼끝 대립'""",False,none,none
4,1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각...,[DA:이슈] ‘구하라 비보’ 최종범 항소심에 영향?…법조계 “‘공소권 없음’ 아냐”,True,gender,hate

In [3]:
train_df.columns

Index(['text', 'title', 'gender_bias', 'bias', 'hate'], dtype='str')

In [4]:
train_df["hate"].value_counts()

hate
none         3486
offensive    2499
hate         1911
Name: count, dtype: int64

In [5]:
def map_label(x):
    if x in ["hate", "offensive"]:
        return 1
    return 0

train_df = train_df.rename(columns={"text": "comments"})
dev_df = dev_df.rename(columns={"text": "comments"})

train_df["label"] = train_df["hate"].apply(map_label)
dev_df["label"] = dev_df["hate"].apply(map_label)
train_df[["comments", "hate", "label"]].head()

                                            comments  hate  label
0  (현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속...  hate      1
1  ....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을...  none      0
2  ...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래...  hate      1
3                 1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데  none      0
4  1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각...  hate      1

In [6]:
train_df = train_df.dropna(subset=["comments"])
train_df["comments"] = train_df["comments"].astype(str).str.strip()
train_df = train_df[train_df["comments"] != ""]
train_df = train_df[train_df["comments"].str.len() >= 3]
train_df = train_df.drop_duplicates(subset=["comments"])

train_df.shape

(7896, 6)